@startuml
'https://plantuml.com/class-diagram
class Object << general >>
Object <|--- ArrayList

note top of Object : In java, every class\n extends this

note "This is a floating note" as N1
note "This note is connected\nto several object." as N2
Object .. N2
N2 .. ArrayList

class Foo
note left : On last defined class

note top of Object
    In java , <size:18>every</size> <u>class</u>
    <b><color:royalBlue> on serveral</color>
    <s>words</s> lines
    And this is hosted by <img:sourceforge.png>
end note
@enduml